### ISSUE TITLE
Loading circle stays up forever if creating first object

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#903] opened 2015-03-04 18:37 UTC
If you create a CNAME/MX/whatever for the first time in a container (as in, none exist yet in said container), the form stays there and the loading circle just keeps spinnin'. The object is created, but refreshing the page is the only way to return to the list (of one item) and get rid of the spinning circle.

**Comment by drkitty** [comment] 2015-03-05 18:11
**Duplicate of issue #853.**

**Closed** 2015-03-05 18:13 UTC
Labels: duplicate, low priority, user interface
